ARM: omap2: Fix compile error on pm34xx.c
Recently, a call to omap_pm_apply_min_bus_tput was added to
pm34xx.c.  This caused the following compile error:
  arch/arm/mach-omap2/pm34xx.c: In function 'omap3_pm_init':
  arch/arm/mach-omap2/pm34xx.c:926: error: implicit declaration of function 'omap_pm_apply_min_bus_tput'

Adding an include of plat/omap-pm.h fixes this.

Change-Id: Ia12054a1fb32ef007ab2470f42e19e190c726ee0
Signed-off-by: Scott Anderson <saa@google.com>
Signed-off-by: Ruslan Bilovol <ruslan.bilovol@ti.com>